ranking-agent/strider

- strider/fetcher.py
Following discussion here:
https://github.com/encode/httpx/issues/411
> Attempt to mitigate timeout problem with automat.

- strider/fetcher.py
- strider/kp_registry.py
- strider/query_planner.py
- strider/util.py
This includes fixes uncovered during integration efforts:
* properly convert between to/from snake_case with bmt
and updates required for integration:
* handle null prefix in CURIE preference
* skip dict-valued properties in Cypher SET
> Misc. updates

- requirements.txt
- strider/fetcher.py
- strider/kp_registry.py
- strider/query_planner.py
- strider/result.py
- strider/server.py
Motivated by KP integration efforts
> Sept 2020 updates

- .dockerignore
- .github/workflows/release.yml
- .gitignore
- Dockerfile
- README.md
- docker-compose.dev.yml
- docker-compose.yml
- main.sh
- requirements.txt
Updated Dockerfile Python version.
Created a dev docker-compose file to detect code changes.
Added to requirements.txt.
Created a CI workflow to publish a docker image on releases.
> Fixed Docker and set up CI.

- .pylintrc
- requirements.txt
- strider/fetcher.py
- strider/query_planner.py
- strider/worker.py
Added a .pylintrc using the generation utility.
Fixed style issues and disabled some rules using the pylintrc file.
> Fixed pylint errors for fetcher and query_planner

- strider/query_planner.py
- tests/server/test_server.py
Added test for plan endpoint. Also modified defaults for functions to ensure logger isn't required.
> Fixed plan endpoint

- strider/query_planner.py
- strider/util.py
- tests/helpers/utils.py
- tests/query_planner/ex2_qg.json
- tests/query_planner/test_query_planner.py
Added a filtering step so that we aren't generating permutations for types that we don't have KPs to solve. Also added tests for timing how long the planning step takes.
> Permutation changes

- strider/logging.py
- strider/server.py
- tests/server/test_server.py
Added a parameter for log level for the /query and /query_result endpoints. The default level is error.
> Logging parameter (updated)

- tests/helpers/utils.py
- tests/query_planner/test_query_planner.py
Moved the load_kps method into the utilities file.
> Test Refactoring

- strider/fetcher.py
- strider/query_planner.py
- strider/server.py
- tests/helpers/utils.py
- tests/query_planner/test_query_planner.py
- tests/query_planner/treated_by_kp.json
- tests/server/test_server.py
- Added tests to make sure that we handle pinned nodes properly
- Changed generate_plan to generate_plans
- Modified generate_plans to properly handle nodes that aren't connected to any other nodes
- Added a utility to help make tests with query graphs more concise using the Mermaid syntax
> Pinned Node Fixes

- README.md
- manage.py
Added management script and updated README with instructions on how to use it.
> Management Script

- requirements-test.txt
- strider/fetcher.py
- strider/server.py
- strider/trapi.py
- strider/util.py
- tests/compatibility/test_compatibility.py
- tests/server/test_server.py
Allows query graphs with list properties (category, id, predicate). Fixes #60.
> List fixes

- requirements-test.txt
- tests/compatibility/test_compatibility.py
- tests/helpers/context.py
- tests/server/test_server.py
Updated tests to use new version of simple-kp with data strings.
> KP Test Changes

- docker-compose.yml
- redis/Dockerfile
- redis/redis.conf
- strider/compatibility.py
- strider/fetcher.py
- strider/server.py
Improved logging so that we don't run into issues with Redis memory.
> Logging Optimizations

- tests/helpers/context.py
- tests/helpers/normalizer.py
- tests/helpers/utils.py
- tests/server/test_server.py
Added ability to specify normalizer data using a string format.
> Normalizer Overlay Changes

- strider/query_planner.py
- strider/util.py
- tests/query_planner/test_query_planner.py
- tests/server/test_server.py
Modified planning algorithm to handle loop support. Added tests for both planning and solving loops.
> Loop Support

- requirements.txt
- strider/query_planner.py
- tests/query_planner/test_query_planner.py
Switched to a planning using a reified graph where all query graph nodes and edges are represented as nodes.
> Reified Query Planning

- strider/query_planner.py
- tests/query_planner/test_query_planner.py
Fixed issue where double sided predicate adds a KP four times to the plan. Added a test and a fix.
> Fixed double-sided predicate

- tests/helpers/utils.py
- tests/query_planner/test_query_planner.py
Added helper functions for validating the contents of plans in a more strict way. Right now, these functions are only used for one test (to demonstrate their usage) but if we like this structure I can go through and convert the rest of the tests to use this.
> Added functions to help with validating plans

- tests/helpers/utils.py
- tests/server/test_server.py
Added function to validate messages. This function is currently implemented for the solve_ex1 test to demonstrate usage.
> Message validation

- strider/fetcher.py
- strider/query_planner.py
- tests/helpers/utils.py
- tests/query_planner/test_query_planner.py
- tests/server/test_server.py
Switched query planning to use KPs for permutations. Also added an optimization to not use copy.deepcopy during the permutations.
> Switched permutations to use KPs

- strider/fetcher.py
- strider/query_planner.py
- tests/helpers/utils.py
- tests/query_planner/test_query_planner.py
- tests/server/test_server.py
Fixed issues with the query in #102. This includes the following changes:
- Switched from category and predicate permutations to KP permutations
- Message output verification in some tests
- Permutation code optimization by removing `copy.deepcopy`
> Issue #102 Fix

- strider/util.py
- tests/server/test_server.py
Fixed InternalServerError on predicates that don't exist in the biolink model. Fixes #118.
> Invalid predicate fix

- strider/fetcher.py
- tests/server/test_server.py
> Added conversion of Protein to GeneOrGeneProduct

- strider/fetcher.py
- tests/server/test_server.py
Fixed bug where we were not contacting KPs due to categories that didn't match the plan.
> Contact descendant KPs

- requirements.txt
- run.py
- strider/config.py
- strider/storage.py
- tests/server/test_server.py
Added a couple small changes to make it easier to debug a query with pdb:
- Enabled python-dotenv
- Added run.py file
> Local run tweaks

- strider/server.py
- strider/util.py
- tests/server/test_server.py
Added better exception handling that manages CORS headers and returns a TRAPI compliant response. Fixes #87.
> Better exception handling

- strider/trapi.py
- strider/util.py
- tests/helpers/utils.py
- tests/server/test_server.py
- tests/trapi/test_trapi.py
This implements better message merging with custom merging functions for nodes and edges. Currently, edge merging is a bit simplistic (we don't merge edges like CHEBI-treats->MONDO and MONDO-treated_by->CHEBI) but still solves the core issue.
> Message merging

- strider/fetcher.py
- strider/trapi.py
- strider/util.py
- tests/server/test_server.py
- tests/trapi/test_trapi.py
Implemented pinned to pinned queries using results filtering. Fixes #133.
> Pinned-to-pinned query fixes

- strider/fetcher.py
- tests/server/test_server.py
Implemented self edge handing. Currently this isn't the prettiest solution so if you have any ideas on how to improve let me know.
Basic idea is to add in a second node for the KP request body with the suffix `.self` and then remove that suffix from bindings that we get back from the KP.
> Self edges fix

- strider/trapi.py
- tests/test_trapi.py
> Identical attribute merging

- requirements.txt
- strider/compatibility.py
- strider/fetcher.py
- strider/kp_registry.py
- strider/normalizer.py
- strider/server.py
- strider/trapi.py
- strider/util.py
- tests/test_server.py
- Added logging for all HTTP calls that Strider makes
- Added better logging output using extra properties on the LogEntry object
- Bumped reasoner pydantic version
> Logging improvements

- strider/compatibility.py
- strider/fetcher.py
- strider/trapi.py
- tests/helpers/utils.py
- tests/test_server.py
Added support for sending multiple identifiers with the same prefix to KPs. This fixes #72.
> Multiple identifier support

- requirements-lock.txt
- requirements-test-lock.txt
- requirements-test.txt
- tests/helpers/context.py
- tests/helpers/normalizer.py
- tests/test_compatibility.py
- tests/test_query_planner.py
urllib3 got updated somehow, too.
> Remove small-kg test dependency

- requirements-lock.txt
- requirements-test-lock.txt
- requirements-test.txt
- requirements.txt
- strider/server.py
- tests/helpers/context.py
- tests/test_server.py
Adds and tests asyncquery endpoint.
Resolves: #252. Register in SmartAPI to resolve #255
> Adding Async Query

- strider/trapi.py
- strider/trapi_throttle/throttle.py
- tests/test_query.py
> Handle symmetric, non-canonical predicates

- strider/compatibility.py
- strider/trapi.py
- strider/util.py
- tests/test_server.py
> Remove ChemicalSubstance shims

- strider/config.py
- strider/trapi.py
- tests/test_query.py
Implements and tests gene protein conflation. Closes #257
> Gene protein conflation

- benchmarks/__main__.py
- manage.py
- requirements-test-lock.txt
- requirements-test.txt
- strider/util.py
- tests/helpers/utils.py
Added command `manage.py benchmark` to run a set of benchmarks. Currently benchmarks the `merge_messages` function.
> Benchmarking

- strider/trapi_openapi.py
> add x-translator.infores field

- strider/config.py
- strider/server.py
> add x-location

- requirements-test-lock.txt
- requirements-test.txt
- strider/server.py
- tests/test_server.py
decision based on ARAGORN call 7/29/2022
strider will send a response in the format of: 
```
{
"message": {},
"status_communication": {
"strider_multiquery_status": "complete"
}
}
```
> add strider multiquery status update

- strider/config.py
- strider/server.py
> Max process time

- requirements-lock.txt
- requirements.txt
- strider/server.py
fixes edge binding issue in #408
> Fix edge bindings

- strider/fetcher.py
- strider/server.py
This will help us fix specific bad cache entries
> Override cache

- strider/fetcher.py
- strider/knowledge_provider.py
- strider/normalizer.py
- strider/throttle.py
- strider/trapi.py
- tests/helpers/mock_responses.py
- tests/test_fetcher.py
Fixes some bugs in the filter messages function where subclasses of pinned nodes weren't getting filtered out correctly and UMLS nodes were being incorrectly filtered out with a valid information content.
Added a test that sends queries all the way through Fetcher.
> Filter messages bug

- strider/server.py
This is just for the infores catalog work, so a catalog can easily be kept of which KPs we are using
> Kp endpoint
