ranking-agent/strider

strider/compatibility.py
strider/fetcher.py
strider/util.py
tests/compatibility/test_compatibility.py

- Switched to contacting KPs with a Query object instead of a Message
- Validate node normalizer responses to ensure they are not None
- Added unlimited timeout for KP calls

Fixed issues with contacting KPs and normalizer

---

strider/query_planner.py
tests/helpers/utils.py
tests/query_planner/test_query_planner.py

Fixed issue where we were not traversing predicates correctly in the reverse direction. We do this by adding edges temporarily in the planning step to ensure that we cover plans that use edges in the opposite direction.

Predicate Directionality Fix

---

strider/fetcher.py
tests/server/test_server.py

If you send a query graph with no predicate for an edge, strider gives a 500. 
Added a little bit that replaces empty predicates with 'biolink:related_to'.
Not sure I did it in the best place, and I don't especially like hardcoding the top predicate.
But it works, and there's a test.

fix for missing predicate in query graph

---

tests/helpers/logger.py
tests/query_planner/test_query_planner.py
tests/server/test_server.py

Added utilities for verifying log contents in each test to ensure we fail tests if there are unexpected warnings or errors. 
(This should catch an issue when combined with #57 😄)

Verify log contents in tests

---

strider/query_planner.py
tests/helpers/utils.py
tests/query_planner/test_query_planner.py

Fixed issue where both forward and reverse edges were included in plans. Also updated kps_from_string method to allow multiple line definitions of a single KP.

Fixed reverse and forward edges in plans

---

strider/server.py
tests/server/test_server.py

Plan endpoint was trying to use a tuple as a JSON key and was therefore throwing a 500 error. This replaces the tuple with a simple string key format (`n0-e01->n1`).

Fixed plan endpoint

---

requirements-test.txt
strider/fetcher.py
strider/trapi.py
tests/helpers/utils.py
tests/server/test_server.py
tests/trapi/test_trapi.py

Added a test to ensure that if we receive duplicate results from a KP the results will not be added multiple times to the resulting message. De-duplication is implemented using the Pydantic Result model.

Result deduplication

---

strider/fetcher.py
strider/query_planner.py
strider/server.py
strider/trapi.py
strider/worker.py
tests/query_planner/test_query_planner.py
tests/server/test_server.py

Fixed #62 where the category given does not match the one that is in the normalizer. The fix involves passing the expanded query graph into StriderWorker and then using that for partial results.

Category Normalizer Mismatch

---

strider/query_planner.py
strider/util.py
tests/query_planner/test_query_planner.py
tests/server/test_server.py

Updated query planning to handle symmetric and inverse predicates. This involved removing the `operation_kp_map` object and instead using the operation graph to hold KP information. 
Right now because BMT is not updated the symmetric predicate test will fail. To force the test to pass, you can add the following code to the `WrappedBMT.predicate_is_symmetric` method:
```python
if predicate_old_format == "correlated_with":
return True
```

Symmetric & Inverse Predicate Handling

---

strider/fetcher.py
strider/query_planner.py
strider/server.py
strider/trapi.py
strider/util.py
tests/query_planner/test_query_planner.py

Added a test for a case where the query graph includes related_to and we need to subclass related_to in both forward and reverse directions. Implemented this change by switching query graph permutations to operation graph permutations.

Descendant Reverse Fix

---

docs/TESTING_INFRASTRUCTURE.md

Added a write-up about the testing infrastructure to a docs folder. Rendered version can be viewed [here](https://github.com/ranking-agent/strider/blob/testing-infrastructure-docs/docs/TESTING_INFRASTRUCTURE.md).

Testing Infrastructure Documentation

---

strider/compatibility.py
tests/compatibility/test_compatibility.py
tests/server/test_server.py

Fixed issues with KP and Normalizer requests that had network errors not being handled properly. Also added tests for these cases. This should fix #112.

Request error handling

---

tests/server/test_server.py

Switched from calling sync_query to using a `httpx.AsyncClient` for testing. The advantage is that we can catch cases here where our code produces an invalid response that should fail to validate. Previously, tests like this could pass incorrectly. 
Also removed the check for warnings in the output logs in favor of asserting that the response contains results.

Implemented test client

---

strider/trapi.py

Some KPs return category lists like this for KNodes: 
```
["biolink:NamedThing", "biolink:MolecularEntity"..."biolink:Disease"]
```
So we have to validate any of these categories against the QNode rather than all. Fixes #78.

Switched all->any for knode category validation

---

strider/fetcher.py
strider/server.py
strider/storage.py
tests/test_server.py

This has a few benefits:
* Redis connections are tied to requests
* We don't need the configuration hack during testing
* We may be able to remove the Redis URL configuration entirely
and one drawback:
* We have to pass the client around everywhere

Convert Redis client to FastAPI dependency

---

requirements-lock.txt
strider/compatibility.py
tests/test_server.py

Added testing for provenance and adjusted edge attributes to report provenance for strider while also preserving provenance from KP's. Test ensures that provenance is included within edges.
Note:
Test may need to be adjusted if simple-kp/binder-kp appropriately reports KP name. Currently, it doesn't look like it does that correctly.

Reformat provenance

---

strider/config.py

url for node norm has changed to nodenormalization-sri-dev.renci.org

---

requirements-lock.txt
requirements-test-lock.txt
requirements-test.txt
requirements.txt
strider/compatibility.py
strider/fetcher.py
strider/query_planner.py
strider/server.py
strider/util.py
tests/test_server.py

We seem to have been spending a lot of time managing the thousands of asyncio tasks. Now we have one "thread" per set of qedge-KP pairs. For example, for a two-hop query, we could have a thread for e0/KG2 + e01/ICEES.
This also works on improving logging.

Batch Strider threads for speed

---

strider/trapi.py
tests/test_trapi.py

This PR targets attribute deduplication, a piece of code that is particularly slow for some queries (see #276). The fix here was to speed up deduplication by switching from a JSON based comparison to a custom hash function. This results in about a 40% speedup on #276. Unfortunately, this is not enough of a speedup to enable smart attribute merging, so for now this is disabled.

Attribute comparison optimization

---

README.md
requirements-lock.txt
requirements.txt
strider/config.py
strider/profiler.py
strider/server.py

This PR adds a profiler that can be enabled with PROFILER=true environment variable. The profiler is available at localhost:5781/profiler and the generated profiles can be used with snakeviz for easy performance debugging. Fixes #277.
The only minor issue of this PR is that yappi is added to our deployed Dockerfile. There's not really a clean way to include it as a dev dependency (this would involve creating `requirements-dev.txt` and `requirements-dev-lock.txt` and `Dockerfile.dev`). I don't think it's going to be a big issue - yappi has no dependencies of its own and is not imported if PROFILER=true is not defined.

Add profiler

---

.gitignore
docker-compose.dev.yml

Fixed a volume path issue in our docker-compose.dev.yml file. This was causing two issues:
* Automatic restarts on code changes were not working because the volume was not mounted in the correct place
* Passthrough of .env file for strider configuration wasn't working
Also updated .gitignore. Closes #281.

Compose volume path fix

---

strider/kp_registry.py

Add hard-coded list of allowed maturities to kp registry search call based on own maturity level. This is pretty hacky to get it working quickly.
Corresponding PR: https://github.com/ranking-agent/kp-registry/pull/26
@cbizon

Add maturity list to kp registry search

---

Dockerfile

Right now queries longer than 30s are failing because of Gunicorn worker timeout.

Added unlimited timeout to gunicorn worker

---

.github/workflows/dev.yml
manage.py

Added separate `lock` and `upgrade` commands to make it possible to install dependencies without upgrading all dependencies to latest version. Also added a check for PRs to make sure that lockfiles are up-to-date.

Dependency Management Command Fix

---

strider/server.py

Strider is throwing httpx:WriteTimeout and/or httpx:ReadTimeout errors when posting results to a callback when using the /asyncquery endpoint. 
Some queries create results that may be in excess of 100mb. it may be in some cases that the data cannot be transferred successfully within the default timeout period (5 seconds). 
the method "async def server.py/async_lookup()" is used to respond to the callback with results that strider has accumulated. in this function the call to "httpx.AsyncClient()" does not have a timeout specified. the modification suggested in this PR increases the timeout to 10 minutes which, in my experience, works well in high latency networks.
please see the enclosed query graph as an example input. to the strider /asyncquery endpoint …

increasing async write timeout

---

strider/trapi.py

This seems to be an issue in the Biolink Model, where `decreases_activity_of` has an inverse that is `activity_decreased_by`. Strider logic looks for the canonical predicate of the two, but neither is. In that case, we were still just flipping the predicate, and RTX doesn't have any results for `activity_decreased_by`. This PR just adds logic to check if the inverse is canonical, and if neither is, then we'll just use the original predicate given to us. We're also going to open an issue on Biolink Model to have them add the canonical property to one of these inverse predicates.

Fix bug where neither inverse predicate is canonical

---

strider/trapi_throttle/trapi.py

This fixes an issue that is present among some multi-hop queries by properly utilizing pydantic models in trapi throttle. This should also close #353 and #354. 
However, this does bring up another pressing issue. When this error was present, strider would error out and then hang until reset. We need to have more robust error handling to ensure that this is not an issue in the future.

use correct pydantic model fields in trapi throttle

---

docs/FETCHER.md
strider/fetcher.py
tests/test_server.py

Fixes a bug in `fetcher.py` that caused unnecessary nodes to appear in kgraphs provided by `lookup()`. The fix helps merge time.
The fetcher was unintentionally adding nodes and edges to the same intermediate kgraph used across multiple results, causing the size of the kgraph to grow with each subsequent result. We're now deepcopying the initial intermediate kgraph for separate use in each result.

Fix independent results bug

---

strider/normalizer.py

This PR fixes the strider 500 on a bad query as mentioned in #362.
However, doing this also has some odd effects. For one thing, we actually do get some results now, which doesn't make sense to me. I don't really know how or why any KP would be sending us anything, but we are receiving response with 23 results back from Genetics KP. This clearly shouldn't be happening.

500 on bad query

---

requirements-lock.txt
requirements-test-lock.txt
requirements-test.txt
requirements.txt
strider/compatibility.py
strider/fetcher.py
strider/trapi_throttle/throttle.py
tests/helpers/context.py
tests/helpers/utils.py
tests/test_kp_responses.py
tests/test_server.py

There are a few things that this PR takes care of:
- Even when there were no curies in the message, we were sending an empty list to Node Norm, who would error. There are now checks for an empty list and we won't send the request.
- We've bumped reasoner-pydantic versions to fix some validation issues
- I removed the pinned kp-registry and binder versions in our testing requirements so we're using the most recent. I also updated the tests because they were using an old kp-registry version.
- To fix the strider hanging issue, I added a debug call stack so we can hopefully find any hangs in the future easier. I also added a generic `Exception` handler to the throttle so we handle errors more gracefully.

Fix hanging bug

---

requirements-lock.txt
requirements.txt
strider/caching.py
strider/config.py
strider/fetcher.py
strider/node_sets.py
strider/server.py
strider/trapi_throttle/throttle.py
tests/helpers/redisMock.py
tests/test_node_sets.py

This PR is aimed at improving the performance and speed of Strider.
- Testing a creative mode query with 83 sub-queries
- No Cache: In the previous version, it was approximately 97 minutes to complete all queries, with the new it takes about 20 mins
- With Cache: previous version I cut it off at 45 mins but I expect it would have taken at least another 15. With the new, it takes about 8 minutes.
- We are now compressing all the entries in redis. This will cut down our storage footprint by ~5x. The plan for deployment is to also bump the redis container up from 10GB to 100GB? With that, we could probably also bump up the TTL on each key from 1 week to something a little longer? @cbizon @kennethmorton do you guys have thoughts on this?

Improve performance

---

strider/caching.py
strider/fetcher.py
strider/knowledge_provider.py
strider/server.py
strider/throttle.py

Adds a check for `timeout_seconds` inside of request `parameters` sent from Aragorn. This will enable Strider to take longer for kp lookups to provide more thorough answers that get cached in Aragorn.
We're also adding a `/clear_cache` endpoint so someone can easily clear the onehop cache.

Timeout param

---

strider/normalizer.py

Try and use the preferred curie from node norm. The preferred prefixes from KPs aren't guaranteed to be ordered correctly.

Try and use preferred curie from NN

---

strider/caching.py
strider/fetcher.py
strider/query_planner.py
strider/server.py

One thing to note is that if the cache isn't available, Strider will get a new registry of kps for every single query. This is very suboptimal, but would allow us to respond in real time until we could get the redis back up.

Add error handling for cache connection errors

---

docker-compose.yml
redis/Dockerfile
requirements-lock.txt
requirements.txt
strider/server.py

The watchdog tests have been failing for a little while because the /kps endpoint was returning a 500. This fixes that.

Change kp refresh function name and pin redis version
